name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/books-project
            git pull origin main

            source venv/bin/activate
            pip install -r requirements.txt

            pkill -f "uvicorn" || true

            nohup uvicorn src.main:app --host 127.0.0.1 --port 8000 --reload > app.log 2>&1 &